[build]
  publish = "build"
  command = "bash generate_pickles.sh && streamlit run app.py"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"

[build.environment]
  PIPENV_VENV_IN_PROJECT = true

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  PYTHON_VERSION = "3.8"

[build.processing]
  skip_processing = true

[siteInfo]
  id = "your_site_id"
  name = "Your Site Name"
  description = "Description of your site"


