[build]
  # Directory to deploy after build process
  publish = "build"

  # Build command to execute
  command = "bash generate_pickles.sh && streamlit run app.py"

[build.environment]
  # Optional environment variables for build process
  PIPENV_VENV_IN_PROJECT = true

[functions]
  # Optional settings for serverless functions
  node_bundler = "esbuild"

[context.production.environment]
  # Optional environment variables for production context
  PYTHON_VERSION = "3.8"

[build.processing]
  # Optional settings for build processing
  skip_processing = true

